bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
rvm:
  - rbx-2
  - jruby
  - jruby-head
  - ruby-head
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
# before_install:
#   - apt-get update
#   - apt-get install idn
sudo: false
