bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
rvm:
  - jruby-9.1.17.0
  - jruby-9.2.6.0
  - truffleruby
  - ruby-head
  - ruby-head-clang
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.2
matrix:
  include:
    - gemfile: gemfiles/Gemfile.public_suffix_2
      rvm: 2.5.5
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang
  fast_finish: true
before_install:
  - sudo apt-get update
  - sudo apt-get install libidn11-dev
