bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
rvm:
  - jruby-9.0.5.0
  - jruby-9.1.7.0
  - ruby-head
  - ruby-head-clang
  - 2.0.0
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang
  fast_finish: true
before_install:
  - gem update bundler
#   - apt-get update
#   - apt-get install idn
sudo: false
