before_install:
 - sudo apt-get update
 - sudo apt-get install idn
bundler_args: --without development
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
