bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
rvm:
  - jruby-9.0.5.0
  - jruby-9.1.5.0
  - ruby-head
  - ruby-head-clang
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - 2.3.1
  - ruby-2.4.0-preview2
  - ruby-2.4.0-preview2-clang
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang
    - rvm: ruby-2.4.0-preview2
    - rvm: ruby-2.4.0-preview2-clang
  fast_finish: true
before_install:
  - gem update bundler
#   - apt-get update
#   - apt-get install idn
sudo: false
