language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby
  - jruby-head
  - rbx-2
  - ree
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
before_install:
 - sudo apt-get update
 - sudo apt-get install idn
