bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
rvm:
  - 2.7.0
before_install:
  - sudo apt-get update
  - sudo apt-get install libidn11-dev
  # https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - if [ -n "${BUNDLER_VERSION+x}" ];
    then
      gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true;
      gem uninstall --all --executables bundler || true;
      gem install bundler -v ${BUNDLER_VERSION};
    fi
